title: "RANGUEBAYE Nantara"
logo: img/05.jpg
description: "Portfolio Expert Réseaux, Infrastructures et Sécurité"
show_downloads: true
theme: jekyll-theme-minimal-mistakes
remote_theme: LeNPaul/portfolio-jekyll-theme
lang: fr
