# Informations générales du site
title: "RANGUEBAYE Nantara"
description: "Portfolio Expert Réseaux, Infrastructures et Sécurité (ERIS)"
lang: fr
logo: img/05.jpg
show_downloads: true

# Thème (GitHub Pages compatible)
theme: jekyll-theme-minimal-mistakes
minimal_mistakes_skin: "air"
minimal_mistakes_version: 4.25

# Menu de navigation
navigation:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/about/"
  - title: "Compétences"
    url: "/skills/"
  - title: "Projets"
    url: "/projects/"
  - title: "Expériences"
    url: "/experience/"
  - title: "Contact"
    url: "/contact/"

# Réseaux sociaux
social:
  github: "https://github.com/ton-github"
  linkedin: "https://www.linkedin.com/in/ranguebaye-nantara-84957b2b6"
  twitter: "https://twitter.com/ton-twitter"  # si tu veux ajouter

# Blog / pagination (si tu veux ajouter articles)
paginate: 5

# Options avancées (si besoin)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
